[build]
  functions = "."  # Path to your functions directory (set to root)
  command = "npm install"  # Ensure dependencies are installed

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
