[build]
  functions = "api"  # Path to your functions directory
  command = "npm install"  # Ensure dependencies are installed

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
