[build]
  functions = "api"  # Path to your functions directory
  publish = "public"  # This can be omitted if not using a static site
  command = "npm install"  # Ensure dependencies are installed

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
